spring:
  application:
    name: BitVote
  datasource:
    username: 'postgres'
    password: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/bitvote'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
    port: 8080


