spring:
  application:
    name: BitVote
  datasource:
    username: 'doadmin'
    password: 'AVNS_BpTh1Kbr3pVFsd60olx'
    url: 'jdbc:postgresql://db-postgresql-fra1-16186-do-user-14816902-0.c.db.ondigitalocean.com:25060/bitvote?sslmode=require'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    redis:
      time-to-live: 3600000
      cache-null-values: true
    type: redis
  default:
    user-img: "https://static.vecteezy.com/system/resources/previews/008/442/086/non_2x/illustration-of-human-icon-user-symbol-icon-modern-design-on-blank-background-free-vector.jpg"

server:
    port: 8080
    error:
      include-binding-errors: always
      include-message: always
      include-exception: true

application:
    security:
      jwt:
        secret-key: 367639792F423F4528482B4D6251655468576D5A7134743777217A2543264629
        expiration: 10800000 # 3 hours
        refresh-token:
          expiration: 604800000 # 7 days
      cors:
        allowed-origins: http://localhost:8000


